apiVersion: v1
kind: Service
metadata:
  name: nlb-{{.Values.application.name}}-service
  namespace: default
  labels:
    app: {{.Values.application.name}}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    # To create Network Load Balancer
spec:
  type: LoadBalancer
  selector:
    app: {{.Values.application.name}}
  ports:
    - name: http
      port: 80
      targetPort: 8090
