apiVersion: v1
kind: Service
metadata:
  name: nlb-{{.Values.application.name}}-service
  namespace: default
  labels:
    app: {{.Values.application.name}}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    # To create Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-name: {{ .Values.environment }}-{{ .Values.application.name }}
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.application.name }}-{{ .Values.environment }}
  ports:
    - name: http
      port: 80
      targetPort: 8090
